from codercom/code-server:v2

USER root

RUN apt-get install -y software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.7

RUN curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
RUN python3.7 /tmp/get-pip.py

RUN python3.7 -m pip install numpy pandas scikit-learn matplotlib keras tensorflow

RUN code-server --install-extension ms-python.python
